### PR TITLE
Add seeds

### LINKED ISSUE #9: Create Seed file
- Create dummy content using Faker
- LATER: Use Spotify api to create podcasts and episodes

### PR DESCRIPTION
**Pull request by b-lauren**
closes #9

### CODE REVIEW

**Review by johnjoubert — DISMISSED** [review]
Looks good, we can improve it a little later on 👍

**Review by johnjoubert — APPROVED** [review]
Resolved conflit 👍

**Review by johnjoubert — CHANGES_REQUESTED** [review]
We're going to improve this PR first before merging!

**Review by johnjoubert — APPROVED** [review]
Nice work @b-lauren! Seed is looking great.

**Review by solowresidual — APPROVED** [review]
Seeding it with Prince songs. Love it! :)

**Pull request merged**
