### PR TITLE
Add the relevant routes to the app

### LINKED ISSUE #23: Create resources in routes
- Create routes using resources based on https://docs.google.com/spreadsheets/d/1ENfi6w_4tibaL1oHWKGEcMMcxj4k9ibM2lAtrhtPZjI/edit#gid=0

### PR DESCRIPTION
**Pull request by johnjoubert**
Closes #23

- [x] Added all routes and confirmed they match the [spreadsheet](https://docs.google.com/spreadsheets/d/1ENfi6w_4tibaL1oHWKGEcMMcxj4k9ibM2lAtrhtPZjI/edit#gid=0)

```
  resources :podcasts, only: [:index, :show ]

  resources :episodes, only: [:show] do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end
  get 'recommended', to: 'episodes#recommended'

  resources :reviews, only: [:index, :edit, :update, :destroy]

  resources :favorites, only: [:index, :update, :destroy]

```

### CODE REVIEW

**Comment by johnjoubert** [comment]
@ceinwenkay / @solowresidual please could add your reviews?

**Comment by solowresidual** [comment]
Looks good guys

**Comment by solowresidual** [comment]
Hey, I'm not exactly sure where to log my review here.... but all good from my perspective

**Review by ceinwenkay — APPROVED** [review]
fine

**Review by solowresidual — APPROVED** [review]

**Pull request merged**
