### PR TITLE
photo done

### PR DESCRIPTION
**Pull request by ceinwenkay**
Screenshot 2020-11-24 at 13 06 37

basic layout html and banner css for home page done

### CODE REVIEW

**Comment by solowresidual** [comment]
We're going to break for lunch and wrap container in a separate branch

**Comment by b-lauren** [comment]
looks good

**Comment by ceinwenkay** [comment]
nice pull request

**Review by ceinwenkay — COMMENTED** [review]
fine

**Review by johnjoubert — APPROVED** [review]

**Review by b-lauren — APPROVED** [review]
looks good

**Pull request merged**
